### ISSUE TITLE
Payload Tracker not displaying properly

### ISSUE THREAD

**Issue by h9lk** [CriticalFlaw/flawhud#103]
new vision of capture progress in pl inspires me, try hud_reloadscheme - does not work

![20200810143352_1](https://user-images.githubusercontent.com/32390006/89785120-8c73ed00-db22-11ea-8bab-168da3e3742c.jpg)

![20200810141744_1](https://user-images.githubusercontent.com/32390006/89785127-8e3db080-db22-11ea-8487-1185fe856ab0.jpg)

![20200810140936_1](https://user-images.githubusercontent.com/32390006/89785130-8f6edd80-db22-11ea-86c7-f1b142f21510.jpg)

**Comment by CriticalFlaw** [comment]
Does this happen every time or only sometimes? Also which operating system are you on?

**Comment by h9lk** [comment]
think this problem in sound cache, just cleaned tf2 and after prevention it happened, but it also happens by itself sometimes, windows 8.1 pro

**Comment by CriticalFlaw** [comment]
Can you zip and upload the copy of flawhud that you have so that I can take a closer look? I think there might be an issue in `resource/ui/preload.res` or where the image files for the cart are which would be `materials/hud` and `materials\vgui\replay\thumbnails\cart_icons`

**Comment by h9lk** [comment]
yes of course, thats my [zip](https://yadi.sk/d/YW6f4wdmvhaD7Q) , no problem

**Comment by CriticalFlaw** [comment]
hmm no difference between this and the live version. This happens sometimes and you always play in a 4:3 resolution, right?

**Comment by h9lk** [comment]
right, it's still strange that sometimes points disappear in cp or class bar at the top, most often crap with point happens in attack/defense mode, for example

![20200812154737_1](https://user-images.githubusercontent.com/32390006/90188169-a718c100-ddc3-11ea-909b-df1ce1abe867.jpg)

when u w8t

![изображение](https://user-images.githubusercontent.com/32390006/90330940-7b5f2c00-dfb9-11ea-8dee-084aff510290.png)

**Comment by h9lk** [comment]
fresh strange screenshots 
![20200913163517_1](https://user-images.githubusercontent.com/32390006/93086904-7f599900-f6a0-11ea-9b0c-c30fa1869c90.jpg)

![20200913183034_1](https://user-images.githubusercontent.com/32390006/93086832-605b0700-f6a0-11ea-8494-e50bdada120f.jpg)

**Comment by CriticalFlaw** [comment]
I've seen the bug in the first screenshot but it's so rare and impossible to fix without moving one of the icons so far to the side that it looks weird. 

Second one is another game bug that I think can just be corrected by inputting `hud_reloadscheme` in console

**Comment by CriticalFlaw** [comment]
Not sure what to tell you about the payload tracker. I haven't had any luck reproducing it nor has anyone else reported it to me.

**Comment by h9lk** [comment]
> 
> 
> Not sure what to tell you about the payload tracker. I haven't had any luck reproducing it nor has anyone else reported it to me.

Sadly, constantly not displaying something or not correctly. It isn't solved `hud_reloadscheme`, `record fix; stop` or `snd_restart` - only restarting the game helps and removes visual bugs, but even then not always

**Comment by CriticalFlaw** [comment]
Do you have any other things in your tf/custom folder?

**Comment by h9lk** [comment]
> 
> 
> Do you have any other things in your tf/custom folder?

Yep, i have - nohats-bgum, no explosion smoke script, surface properties &  comanglia's toaster config with ur hud

**Comment by CriticalFlaw** [comment]
Can you reproduce the bug without any of those other addons except for the latest version of flawhud?

**Comment by h9lk** [comment]
> 
> 
> Can you reproduce the bug without any of those other addons except for the latest version of flawhud?

problem - don't know for what reason this happens, it turns out randomly, now I'll try to play without everything except ur hud

**Comment by CriticalFlaw** [comment]
Give it a try. If it doesn't happen again then it's an issue with one of those other addons - otherwise it's an issue with flawhud.

**Comment by h9lk** [comment]
> 
> 
> Give it a try. If it doesn't happen again then it's an issue with one of those other addons - otherwise it's an issue with flawhud.

only thing that so far noticed that  control point display panel began to disappear more often, removed all custom content, 
`hud_reloadscheme` dont work, screenshots were taken on 2 different servers with an interval of 30 minutes

![20200930225023_1](https://user-images.githubusercontent.com/32390006/94733048-d41f3400-036f-11eb-8970-4f5c06a76fb9.jpg)

![20200930224635_1](https://user-images.githubusercontent.com/32390006/94733066-ded9c900-036f-11eb-850e-2aebd5dc179e.jpg)
