### ISSUE TITLE
Add developer commentaries to closed captions

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#122]
The link to the developer commentaries is below.

https://raw.githubusercontent.com/clovervidia/clovervidias-captions/master/resource/closecaption_clovervidiac.txt

**Comment by CriticalFlaw** [comment]
I just thought of something that you may want to check to verify. FlawHUD uses a condensed version of clovervidiac's closed captions, removing all blanks. I'm wondering if those produce console errors such as "Could not find closed caption for X" - if it does then I may just use the full proper version. 

https://github.com/CriticalFlaw/FlawHUD/blob/master/resource/closecaption_english.txt

**Comment by CriticalFlaw** [comment]
Updated the closed captions, below are all the changes. Thank you for the suggestion:
- Added developer commentary captions.
- Updated class specific captions to use high-contrast colors.
- Fixed "missing caption" errors and captions going offscreen.

**Comment by Tiagoquix** [comment]
You forgot to change the `"Language"	"clovervidia"` to `"Language"	"english"`.
Also, don't you think that the closed captions without class-specific colors are better?

There is a version of Clovervidia Captions that is competitive but without class-specific colors. The link is below.

https://raw.githubusercontent.com/clovervidia/clovervidias-captions/master/resource/closecaption_clovervidiaw.txt

@CriticalFlaw

**Comment by CriticalFlaw** [comment]
I'll change it to English later. It won't stop you from using the closed captions when enabled.

No, I think color specific captions are better because you can become familiar with each color and at a glance know which class the caption is about without reading.

**Comment by Tiagoquix** [comment]
> I'll change it to English later. It won't stop you from using the closed captions when enabled.

It will. When closed captions are enabled and `cc_lang`'s value is empty (its default value), it will read the `cl_language` cvar to determine in which language the closed captions should be displayed by the game.

* cc_lang - Current close caption language (emtpy = use game UI language)
https://developer.valvesoftware.com/wiki/List_of_TF2_console_commands_and_variables

> No, I think color specific captions are better because you can become familiar with each color and at a glance know which class the caption is about without reading.

Alright.

**Comment by CriticalFlaw** [comment]
Weird. Because I was able to test the closed captions without issues or any additional changes except putting in `closecaption 1` into console. But sure, I've pushed the change here: https://github.com/CriticalFlaw/FlawHUD/commit/e4f45a6c26c28efec04c71fe4fd9dece69ee2fc4
