### ISSUE TITLE
Target damage is misplaced and code-pro font is not rendering

### ISSUE THREAD

**Issue by pingas12345** [CriticalFlaw/flawhud#136]
Hello, I am not sure if this is an issue with the installer or with the hud in general but I had just updated the installer, made some edits to my hud and reinstalled it, but opening TF2 I found that the gamemode selection selection widget is sliding from below instead of from the right like how TF2's default hud does (and how the previous Flawhud version worked), and when I join a match damage dealt to a target will appear way below and almost out of sight instead of above as usual. What gives?

Thanks for your help.

Attached are examples of my issue

![Inked20201128004659_1_LI](https://user-images.githubusercontent.com/64357461/100455987-c25dd100-3113-11eb-8112-8a7150f26e56.jpg)
![20201128004817_1](https://user-images.githubusercontent.com/64357461/100456003-c7228500-3113-11eb-9b94-92125bbae7f4.jpg)

**Comment by CriticalFlaw** [comment]
Hello. Please remove your current installation of flawhud and install a fresh version. There may be a file conflict somewhere.

The sliding dashboard is a new design, just that it's not showing any text for some reason.

**Comment by pingas12345** [comment]
I've deleted flawhud from tf/custom and reinstalled it with the installer and still no difference, with no text and damage still appearing glitched.

**Comment by pingas12345** [comment]
Here's what the settings in the installer look like

![image](https://user-images.githubusercontent.com/64357461/100458408-d73c6380-3117-11eb-9ea4-b11b1ba82645.png)

Edit: turns out unticking Code Pro Fonts fixes the text not appearing in the dashboard but my target damage text appears below

**Comment by CriticalFlaw** [comment]
Try doing a refresh one more time please. I've just pushed the commit https://github.com/CriticalFlaw/FlawHUD/commit/8064707ab5fda89c3fbaf6117fe15d58de2d7be2 which adds the missing font entry for Code Pro and the updated damage value position. Sorry for the inconvenience.

**Comment by pingas12345** [comment]
The damage value still appears for me floating below and not above the target, even after deleting and reinstalling the HUD.
However, the Code Pro font works in the dashboard as intended now.

**Comment by CriticalFlaw** [comment]
What happens if you enable the alternate player stats option, see where the damage values lands then revert back. 

I'm not getting this damage value misplacement, so something must be getting screwy somewhere

**Comment by pingas12345** [comment]
I am getting the same result with the alternate player stats option ticked. I've attached a better example of my issue if necessary.
The one circled is the damage that is presented over the enemy target and accumulated. It is showing underneath in some weird position below me and obscures itself weirdly as well.

Just a small note, I won't be replying for another 8-9 hours due to sleep so the issue would be put on hold till I wake up for more testing.

![Inked20201128025223_1_LI](https://user-images.githubusercontent.com/64357461/100466551-2fc62d80-3125-11eb-97fe-94aab106212e.jpg)

**Comment by CriticalFlaw** [comment]
Oh I see. It's not the value shown on your HUD but the one you'd expect to see over your target.

**Comment by pingas12345** [comment]
Yes, precisely

**Comment by CriticalFlaw** [comment]
Thank you for clarifying. I've pushed an update for both FlawHUD and the Installer (pulled the old version so just download it again from the Release page) which corrects the damage positioning for all modes (default, lowered and alternate).

**Comment by pingas12345** [comment]
Thank you, reinstalling it fixes it now
