### ISSUE TITLE
Overlapping Uber and MVM Shield bar

### ISSUE THREAD

**Issue by thejaviertc** [CriticalFlaw/flawhud#347]
The uber and MVM Shield bar overlaps and are misplaced

![imagen](https://github.com/CriticalFlaw/flawhud/assets/45662206/28b1bcf9-d1e8-4523-bd94-8edf5836923e)

**Comment by CriticalFlaw** [comment]
Fixed in 955234cba39e32b7bbcba8a20e2f3f5b7777e494. Thanks.

**Comment by Presto06** [comment]
> Fixed in [955234c](https://github.com/CriticalFlaw/flawhud/commit/955234cba39e32b7bbcba8a20e2f3f5b7777e494). Thanks.

![image](https://github.com/CriticalFlaw/flawhud/assets/123919000/ffe80555-bd5e-4de9-bbd4-2ada91b8589c)

Issue is still present with the vaccinator (the icons), may not be worth fixing though if fixing the vaccinator messes up other mediguns

**Comment by CriticalFlaw** [comment]
Yeah I saw it and don't plan on fixing

**Comment by Presto06** [comment]
This is still bugged for me even after a fresh install through the editor

**Comment by CriticalFlaw** [comment]
Fixed in the editor here: https://github.com/CriticalFlaw/TF2HUD.Editor/commit/07ca468fbf5561b4df211d331bb3a00a2f8be54c
