### ISSUE TITLE
Missing localizations on the Mann Co. Store

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#75]
![image](https://user-images.githubusercontent.com/30274161/75723014-3325a900-5cba-11ea-9a50-85a447055da3.png)

"Exit Store" and "Try It Out" are not localizated in the HUD files.
"Back" is not too.

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/FlawHUD/commit/871ffdfec4657061bebb72e9b4b33247ef245b86

**Comment by Tiagoquix** [comment]
@CriticalFlaw What about "Exit Store"? It is still not localizated.

**Comment by CriticalFlaw** [comment]
That one uses the Q key as a shortcut, which does not exist in the localization file. I'll look into a workaround later.
